### ISSUE TITLE
Will it renew the TLS certificate?

### ISSUE THREAD

**Issue by pearj** [wernerhp/ha.addon.acme_sh#1]
I’ve looked through the Dockerfile and run.sh and I can’t see how it will renew the TLS certificate. Ie I don’t see it running cron in the background or anything like that. 

Is cron magically running or is renewals a todo?

I’m new to Home Assistant plug-ins so apologies if this is an obvious question.

**Comment by wernerhp** [comment]
@pearj There is no cron.  You can setup a Home Assistant Automation to run the Add-on when you need it to.
See https://www.home-assistant.io/docs/automation/basics/
Example
```
- id: renew-certificate
  alias: Renew Certificate
  trigger:
  - platform: time
    at: 00:00
  action:
  - service: hassio.addon_restart
    data:
      addon: bea82187-acme-sh
  initial_state: true
  mode: single
```
